name: build-react

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install

      - name: Build React app
        env:
          REACT_APP_USERNAME: ${{ secrets.REACT_APP_USERNAME }}
          REACT_APP_PASSWORD: ${{ secrets.REACT_APP_PASSWORD }}
          REACT_APP_AIRFLOW_TEST: ${{ secrets.REACT_APP_AIRFLOW_TEST }}
          REACT_APP_AIRFLOW: ${{ secrets.REACT_APP_AIRFLOW }}
          REACT_APP_DOCKER_REGISTRY: ${{ secrets.REACT_APP_DOCKER_REGISTRY }}
          REACT_APP_GRAFANA: ${{ secrets.REACT_APP_GRAFANA }}
          REACT_APP_FIRST2DATA: ${{ secrets.REACT_APP_FIRST2DATA }}
          REACT_APP_FIRST2DATA_TEST: ${{ secrets.REACT_APP_FIRST2DATA_TEST }}
          REACT_APP_SHAREPOINT: ${{ secrets.REACT_APP_SHAREPOINT }}
          REACT_APP_FIRST2PROJECT: ${{ secrets.REACT_APP_FIRST2PROJECT }}
          REACT_APP_IVUE: ${{ secrets.REACT_APP_IVUE }}
          REACT_APP_HELP_DESK: ${{ secrets.REACT_APP_HELP_DESK }}
          REACT_APP_VIRUS_TOTAL: ${{ secrets.REACT_APP_VIRUS_TOTAL }}
          REACT_APP_MIMECAST: ${{ secrets.REACT_APP_MIMECAST }}
        run: npm run build

on:
  push:
    branches:
      - master
